### ISSUE TITLE
the app crashes on the first start

### ISSUE THREAD

**Issue by friofry** [six78/2-story-points-cli#33]
I've installed the release version 
then I ran ./2sp from the command line and got this error:

```
 ☠️ fatal error: failed to create waku node
panic: runtime error: invalid memory address or nil pointer dereferencewaku-pp-2024-05-29T15-55-30Z.log
[signal SIGSEGV: segmentation violation code=0x2 addr=0x58 pc=0x100dbfac0]

goroutine 832 [running]:
2sp/game.(*Game).LeaveRoom(0x0)
	/Users/runner/work/2-story-points-cli/2-story-points-cli/game/game.go:58 +0x20
2sp/view/commands.QuitApp.func1()
	/Users/runner/work/2-story-points-cli/2-story-points-cli/view/commands/commands.go:148 +0x24
github.com/charmbracelet/bubbletea.(*Program).handleCommands.func1.1()
	/Users/runner/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.25.0/tea.go:294 +0x30
created by github.com/charmbracelet/bubbletea.(*Program).handleCommands.func1
	/Users/runner/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.25.0/tea.go:293 +0x11c

```

The second time it worked perfectly.

**Comment by friofry** [comment]
my local path is `/Users/ricko/status/planner`

**Comment by igor-sirotin** [comment]
@friofry Looks like there are 2 issues:

1. `fatal error: failed to create waku node`.
Can you please take a look in logs for waku connection error details?
You can find logs in `/Users/ricko/Library/Application Support/six78/2sp/logs`. Take the one that matches time.

2. `panic: runtime error: invalid memory address or nil pointer dereference`
From the call stack I can see that you've clicked `Ctrl+C` and the app crashed here:
https://github.com/six78/2-story-points-cli/blob/6fca0f95a083d56760162de7529c950349565bb2/view/commands/commands.go#L148
... because no `Game` was created yet. I will add a `nil` check there 👌
